#=== HOW TO EDIT ===============================================================
#
# hosts:
#   XX.XX.XX.XX:
#   yourdomain.com:
#
# All your hosts (or the only host) to provision for givern group.
# Group names correspond to specific software to be installed and provisioned
# and are described in README
#
# All groups are provisioned with basic configuration described in group_vars/all.yml
#
# Group specific config is in group_vars/<role_name>.yml
#
# Be carefull with spaces, it's YAML baby :)
#
# The most simple case: you use the same VPS host for each group — all live together
#===============================================================================

all:
  children:
    passenger-nginx-app-1:
      hosts:
        XX.XX.XX.XX:
      vars:
        letsencrypt: yes # wether set up SSL for the host

#=============================================
# You can add multiple app groups with unique names `passenger-nginx-app-*`
#    passenger-nginx-app-2:
#      hosts:
#        (same host different app | different host another app):
#
# It's also handy for staging rollout.
#=============================================

    postgres-1:
      hosts:
        yourhost.com:
#        XX.XX.XX.XX:

#===============================================================================
# You can add multiple postgres groups with unique names `postgres-*`
# with their own unique configs
#
#    postgres-2:
#      hosts:
#        (different host for different app or Rails stage):
#===============================================================================

    redis:
      hosts:
        XX.XX.XX.XX:

    postfix-dkim:
      hosts:
        XX.XX.XX.XX:


    #==============================================
    # To skip a group — drop the all its line, or leave just group name
    # Like this (ajenti panel will not be installed):
    #==============================================
    ajenti:
#      hosts:
#        78.46.206.106:


# docs: https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html